### PR TITLE
Fix for a Bug in ShareSellingRound, automatic Bancruptcy Check is now

### LINKED ISSUE #48: Bug in ShareSellingROund
If theres no sellable share on the start of a ShareSellingRound because the Director needs to add cash the game stalls out.

### PR DESCRIPTION
**Pull request by neutronc**
done.

Fix for the bug reported by HansvanderDrift:
A director needing to finance a train in an emergency train buy, cant
act currently if he has zero shares to be sold in the ShareSellingRound
if he does not have sufficient cash to finance the train by himeself
without selling shares. Fixes #48

### CODE REVIEW

File: src/main/java/net/sf/rails/game/financial/ShareSellingRound.java [hunk 1]
```diff
@@ -54,7 +54,15 @@ public void start(RoundFacade parentRound, Player sellingPlayer, int cashToRaise
         this.dumpOtherCompaniesAllowed = dumpOtherCompaniesAllowed;
         log.debug("Forced selling, dumpOtherCompaniesAllowed = " + dumpOtherCompaniesAllowed);
         getRoot().getPlayerManager().setCurrentPlayer(sellingPlayer);
-        getSellableShares();
+        //getSellableShares();
```
Comment (blentz) [inline src/main/java/net/sf/rails/game/financial/ShareSellingRound.java]: No need to comment this out. Just remove it.

**Comment by blentz** [comment]
Overall, this looks fine. Let's just get out of the habit of commenting out lines of code.

**Comment by neutronc** [comment]
Should be fixed now with the latest small commit
